### ISSUE TITLE
Analyze Survey data

### ISSUE THREAD

**Issue by calebjpicker** [calebjpicker/TGAME#52]
we should analyze the survey data, put it into a presentable form, and based upon the conclusions we draw, come up with solutions for problems or ways to improve and so on.

**Comment by MElemental** [comment]
fragment comments into points so that it preserves anonymity, and we can also talk about specific points

**Comment by calebjpicker** [comment]
This is still ongoing.

**Comment by calebjpicker** [comment]
We completed this and presented it.
